title: Una mente deshecha
theme: jekyll-theme-midnight
repository: guiwoda/guiwoda.github.io
future: true
google_analytics: UA-89976619-1

gems:
- jekyll-github-metadata
- jekyll-mentions
- jekyll-redirect-from
- jekyll-sitemap
- jemoji 

owner:
  name: "@guiwoda"
  url: https://twitter.com/guiwoda
